### ISSUE TITLE
404 : Not Found You are requesting a page that does not exist!

### ISSUE THREAD

**Issue by santiago20054** [bbye98/minim#11] opened 2024-03-18 01:27 UTC
I am getting a 404 error when I'm using this code:

```
from minim import spotify
import pandas as pd
client = spotify.WebAPI(flow="pkce", browser=True, web_framework="http.server",
                        scopes=spotify.WebAPI.get_scopes("all"), overwrite=True)

## Specify the target Spotify playlist's ID.
playlist_id = "bff27fb8fb714104"

## Get the first 100 playlist items/tracks.
resp = client.get_playlist_items(playlist_id, limit=100)

## Get the track IDs of the returned playlist items/tracks.
track_ids = [item["track"]["id"] for item in resp["items"]]

## Get the audio features for the 100 tracks.
afs = client.get_tracks_audio_features(track_ids)

## Create a DataFrame using the audio features data.
df = pd.DataFrame(afs)

## Iterate through the rest of the playlist items/tracks.
while True:

    ## Break the loop if all playlist items/tracks have been retrieved.
    if resp["offset"] + resp["limit"] >= resp["total"]:
        break

    ## Same procedure as above.
    resp = client.get_playlist_items(playlist_id, limit=100, 
                                     offset=resp["offset"] + resp["limit"])
    track_ids = [item["track"]["id"] for item in resp["items"]]
    afs = client.get_tracks_audio_features(track_ids)

    ## Concatenate the new audio features data to the existing DataFrame.
    df = pd.concat([df, pd.DataFrame(afs)])
```

I am working on a Jupyter Notebook and when I run the code I get a Spotify webpage with this authorization: 

![image](https://github.com/bbye98/minim/assets/56911524/aec48679-cf33-46dd-94e3-ebc9abb6f3bd)

When I click on agree I get a new page with the error:

![image](https://github.com/bbye98/minim/assets/56911524/2d746d78-769d-487a-9e0f-52466ce4eff8)

Not sure why this is happening. Before this I was getting the RuntimeError: minim.spotify.WebAPI.get_playlist_item() requires the 'playlist-modify-private' authorization scope. I used the overwrite=True paramater but now having the issue I mentioned above.

Hope you can help me. Thanks in advance!

**Comment by bbye98** [comment] 2024-03-18 03:20
The first screenshot with the green "Agree" button looks good. The authorization page lists all possible scopes, which means that both the `flow="pkce"` and `scopes=WebAPI.get_scopes("all")` arguments were accepted.

The 404: Not Found page is a bit concerning. Normally, after clicking "Agree", it should display a simple text page saying "Authorization granted. You may now close this page." or something to that effect. In the background, the `WebAPI` object would then be populated with the access/refresh tokens obtained by exchanging the code you see in the URL (everything after `?code=`).

Can you try running the authentication process in a normal Python script instead of a Jupyter Notebook? Without having direct access to your machine, I can't immediately pinpoint what the issue is.

I just tested on one of my machines that has never had Minim installed, and both the Python script and Jupyter Notebook routes worked fine.

**Comment by bbye98** [comment] 2024-03-20 19:31
@santiago20054 As I have not heard back from you, I will assume that you have resolved this issue. As such, I will be closing this thread!

**Closed by bbye98** 2024-03-20 19:31 UTC
Labels: help wanted
